HMS_P8/Models/ErrorViewModel.cs
namespace HMS_P8.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HMS_P8/Models/Praticien.cs
using System.ComponentModel.DataAnnotations;

namespace HMS_P8.Models
{
    public class Praticien
    {

        public int PraticienId { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public int Specialite { get; set; }
    }
}

HMS_P8/Controllers/HomeController.cs
using HMS_P8.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace HMS_P8.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HMS_P8/Controllers/PraticienController.cs
using HMS_P8.Models;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http;

namespace HMS_P8.Controllers
{
    public class PraticienController : Controller
    {
        public async Task<IActionResult> ListePraticiens()
        {
            // Code pour récupérer la liste des praticiens depuis l'API Gateway
            // Utilisez HTTPClient ou d'autres méthodes appropriées pour appeler votre API.

            // Exemple de code :
            using (var httpClient = new HttpClient())
            {
                var response = await httpClient.GetAsync("https://localhost:7289/ApiGateway/Praticien");

                if (response.IsSuccessStatusCode)
                {
                    // Assurez-vous d'utiliser les bibliothèques appropriées pour la désérialisation
                    // Dans cet exemple, j'utilise System.Text.Json
                    var content = await response.Content.ReadAsStringAsync();
                    var praticiens = System.Text.Json.JsonSerializer.Deserialize<List<Praticien>>(content);

                    // Remarque : Assurez-vous d'inclure la vue correspondante dans le dossier Views/Praticien
                    return View();
                }
                else
                {
                    // Gérez les erreurs de requête ici
                    return View("Error");
                }
            }
        }

    }

    }

HMS_P8/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Accueil";
}


<!--service-->
<section id="service" class="section-padding">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-4">
                <h2 class="ser-title">Notre offre</h2>
                <hr class="botm-line">
                <p>Nos professionnels diplômés d'état possèdent une vaste expérience et expertise, leur permettant de vous accompagner, quelle que soit la nature de vos besoins en soins paramédicaux.</p>
            </div>
            <div class="col-md-4 col-sm-4">
                <div class="service-info">
                    <div class="icon">
                        <i class="fa fa-stethoscope"></i>
                    </div>
                    <div class="icon-info">
                        <h4>Assistance 7 jours sur 7</h4>
                        <p>
                            Nos cabinets à Paris et en région parisienne sont ouverts le samedi et le dimanche pour vous permettre d'accéder à des soins quel que soit le jour de la semaine.
                            Nous proposons un centre de soins spécialisés pour les enfants de moins de 18 ans dans nos cabinets parisiens.
                        </p>
                    </div>
                </div>
                <div class="service-info">
                    <div class="icon">
                        <i class="fa fa-ambulance"></i>
                    </div>
                    <div class="icon-info">
                        <h4>Traitements en urgence</h4>
                        <p>
                            Nos cabinets à Paris et en région parisienne sont ouverts le samedi et le dimanche pour vous permettre d'accéder à des soins quel que soit le jour de la semaine.
                            Nous proposons un centre de soins spécialisés pour les enfants de moins de 18 ans dans nos cabinets parisiens.
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-4">
                <div class="service-info">
                    <div class="icon">
                        <i class="fa fa-user-md"></i>
                    </div>
                    <div class="icon-info">
                        <h4>Recherche paramédicale</h4>
                        <p>Nous investissons dans certains des traitements les plus innovants au monde et contribuons à leur mise au point, afin de vous accompagner au mieux.</p>
                    </div>
                </div>
                <div class="service-info">
                    <div class="icon">
                        <i class="fa fa-medkit"></i>
                    </div>
                    <div class="icon-info">
                        <h4>Soins paramédicaux haut de gamme</h4>
                        <p>Nous investissons dans certains des traitements les plus innovants au monde et contribuons à leur mise au point, afin de vous accompagner au mieux.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--/ service-->
<!--doctor team-->
<section id="doctor-team" class="section-padding">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2 class="ser-title">Faites la connaissance de nos professionnels</h2>
                <hr class="botm-line">
            </div>

            <div class="col-md-3 col-sm-3 col-xs-6">
                <div class="thumbnail">
                    <img src="~/img/doctor1.jpg" class="team-img">
                    <div class="caption">
                        <h3>Jane</h3>
                        <p>Dermatologie</p>
                        <ul class="list-inline">
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="col-md-3 col-sm-3 col-xs-6">
                <div class="thumbnail">
                    <img src="../../img/doctor2.jpg" class="team-img">
                    <div class="caption">
                        <h3>John</h3>
                        <p>Cardiologie</p>
                        <ul class="list-inline">
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>
<!--/ doctor team-->
<a asp-controller="Praticien" asp-action="ListePraticiens">Liste des Praticiens</a>

<!--contact-->
<section id="contact" class="section-padding">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2 class="ser-title">Nous contacter</h2>
                <hr class="botm-line">
            </div>
            <div class="col-md-4 col-sm-4">
                <h3>Contact Info</h3>
                <div class="space"></div>
                <p><i class="fa fa-map-marker fa-fw pull-left fa-2x"></i>32 Boulevard de la Sérénité<br> 75000 Paris</p>
                <div class="space"></div>
                <p><i class="fa fa-envelope-o fa-fw pull-left fa-2x"></i>info@harmonie-sante-paramedical.fr</p>
                <div class="space"></div>
                <p><i class="fa fa-phone fa-fw pull-left fa-2x"></i>+33 01 12 31 23 45</p>
            </div>
            <div class="col-md-8 col-sm-8 marb20">
                <div class="contact-info">
                    <h3 class="cnt-ttl">Vous avez une question ? Vous voulez prendre rendez-vous ?</h3>
                    <div class="space"></div>
                    <div id="sendmessage">Votre message a bien été envoyé. Merci !</div>
                    <div id="errormessage"></div>
                    <form action="" method="post" role="form" class="contactForm">
                        <div class="form-group">
                            <input type="text" name="name" class="form-control br-radius-zero" id="name" placeholder="Vos nom et prénom" data-rule="minlen:4" data-msg="Veuillez entrer 4 caractères minimum." />
                            <div class="validation"></div>
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-control br-radius-zero" name="email" id="email" placeholder="Votre adress email" data-rule="email" data-msg="Veuillez entrer une adresse valable." />
                            <div class="validation"></div>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control br-radius-zero" name="subject" id="subject" placeholder="Objet" data-rule="minlen:4" data-msg="Veuillez entrer 8 caractères minimum." />
                            <div class="validation"></div>
                        </div>
                        <div class="form-group">
<textarea class="form-control br-radius-zero" name="message" rows="5" data-rule="required" data-msg="Veuillez nous écrire un message." placeholder="Message"></textarea>
                            <div class="validation"></div>
                        </div>

                        <div class="form-action">
                            <button type="submit" class="btn btn-form">Envoyer message</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<!--/ contact-->

HMS_P8/Views/Praticien.cshtml
@model List<Praticien>  
<h2>Liste des Praticiens</h2>

<ul>
    @foreach (var praticien in Model)
    {
        <li>@praticien.Nom, @praticien.Prenom</li> <!-- Assurez-vous d'ajuster cela en fonction de votre modèle de Praticien -->
    }
</ul>

HMS_P8/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Harmonie Santé Paramédical</title>
    <meta name="description" content="Free Bootstrap Theme by BootstrapMade.com">
    <meta name="keywords" content="free website templates, free bootstrap themes, free template, free bootstrap, free website template">

    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans|Raleway|Candal">
    <link rel="stylesheet" type="text/css" href="~/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="~/css/style.css">
   
</head>
<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="60">
    <!--banner-->
    <section id="banner" class="banner">
        <div class="bg-color">
            <nav class="navbar navbar-default navbar-fixed-top">
                <div class="container">
                    <div class="col-md-12">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand" href="#"><img src="~/img/logo1.png" class="img-responsive" style="width: 140px; margin-top: -16px;"></a>
                        </div>
                        <div class="collapse navbar-collapse navbar-right" id="myNavbar">
                            <ul class="nav navbar-nav">
                                <li class="active"><a href="#banner">Accueil</a></li>
                                <li class=""><a href="#service">Notre offre</a></li>
                                <li class=""><a href="#doctor-team">Notre équipe</a></li>
                                <li class=""><a href="#contact">Nous contacter</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </nav>
            <div class="container">
                <div class="row">
                    <div class="banner-info">
                        <div class="banner-logo text-center">
                            <img src="~/img/logo1.png" class="img-responsive">
                        </div>
                        <div class="banner-text text-center">
                            <h1 class="white">HARMONIE SANTÉ PARAMÉDICAL</h1>
                            <p>Le paramédical depuis votre bureau.</p>
                            <a href="~/Booking/GetConsultantCalendar" class="btn btn-appoint">Prendre rendez-vous.</a>
                        </div>
                        <div class="overlay-detail text-center">
                            <a href="#service"><i class="fa fa-angle-down"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--/ banner-->
    @RenderBody()
    <!--footer-->
    <footer id="footer">
        <div class="top-footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 col-sm-4 marb20">
                        <div class="ftr-tle">
                            <h4 class="white no-padding">Présentation</h4>
                        </div>
                        <div class="info-sec">
                            <p>Harmonie Santé Paramédical est un prestataire de soins paramédicaux de premier plan. Notre réseau de cabinets s'étend sur tout le territoire et vous donne accès à un vaste choix de spécialités telles que l'ergothérapie, la dietétique, la kinésithérapie, l'osthéopathie, l'orthophonie, et bien d'autres encore. </p>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-4 marb20">
                        <div class="ftr-tle">
                            <h4 class="white no-padding">Liens rapides</h4>
                        </div>
                        <div class="info-sec">
                            <ul class="quick-info">
                                <li><a href="index.html"><i class="fa fa-circle"></i>Accueil</a></li>
                                <li><a href="#service"><i class="fa fa-circle"></i>Service</a></li>
                                <li><a href="#contact"><i class="fa fa-circle"></i>Rendez-vous</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-4 marb20">
                        <div class="ftr-tle">
                            <h4 class="white no-padding">Suivez-nous sur les réseaux sociaux</h4>
                        </div>
                        <div class="info-sec">
                            <ul class="social-icon">
                                <li class="bglight-blue"><i class="fa fa-facebook"></i></li>
                                <li class="bgred"><i class="fa fa-google-plus"></i></li>
                                <li class="bgdark-blue"><i class="fa fa-linkedin"></i></li>
                                <li class="bglight-blue"><i class="fa fa-twitter"></i></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-line">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 text-center">
                        © Harmonie Santé Paramédical. Tous droits réservés
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!--/ footer-->

    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/jquery.easing.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/custom.js"></script>
    <script src="~/contactform/contactform.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>